### ISSUE TITLE
Maldet 1.6.2 is out

### ISSUE THREAD

**Issue by brentclark** [nexcess/puppet-maldet#14]
Good day

Could you please look to managing the 1.6 series of maldet.

**Comment by tedwardia** [comment]
Hey Brent,

That's something we'll be doing. I don't have a timeline for you right now, but we'll be supporting this Soon™.

Thanks,

**Comment by Joshua-Snapp** [comment]
@tedwardia 
Thanks a lot for this Puppet module! We use maldet on a number of servers where I work. I really want to get maldet's installation and configuration managed using your module.

I already forked your project, so I can make the necessary adjustments to take into account the changes that came with version 1.6.

If you don't mind, I'd like to submit pull requests as I work through those changes. I'd rather see these get merged upstream in your repo and hopefully switch away from using my fork at some point.

Thanks again!

**Comment by tedwardia** [comment]
Hey Joshua,

Feel free to open issues and/or PRs about any changes you'd like to make.

Thanks,

**Comment by Samgarr** [comment]
It seems @Joshua-Snapp made nice PRs for maldet 1.6, it is possible to merge these?

**Comment by Joshua-Snapp** [comment]
Can someone please take a look at the 5 PRs I submitted and provide some feedback?

**Comment by Joshua-Snapp** [comment]
@tedwardia Ready and waiting... :)

**Comment by ChrisOrlando** [comment]
Very slow on the response here, but 1.6.x has been supported [since the 3.0.0 release](https://github.com/nexcess/puppet-maldet/releases/tag/3.0.0).
